spring:
  security:
    oauth2:
      client:
        provider:
          my-keycloak-provider:
            issuer-uri: http://localhost:8080/auth/realms/atouts-realm
        registration:
          keycloak-spring-gateway-client:
            provider: my-keycloak-provider
            client-id: atouts-gateway-client
            client-secret: cB9dMFvP57NS6mM2FiGAPM29Rv3znSzw
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/keycloak'

