management:
  health:
    redis:
      enabled: false
logging:
  level:
    org.springframework.cloud.gateway: TRACE

spring:

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: atouts-gateway-client
            client-secret: cB9dMFvP57NS6mM2FiGAPM29Rv3znSzw
            scope: openid

        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/atouts-realm
  session:
    store-type: redis
    redis:
      flush-mode: on_save
      namespace: spring:session
  data:
    redis:
      host: redis-11620.c10.us-east-1-2.ec2.cloud.redislabs.com
      port: 11620
      password: t8CSfCefoozRej8KelfXuLr7VdvzeKCJ
      username: default
  cloud:
    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
            - GET
            - POST
            - PUT

      default-filters:
        - SaveSession
      routes:
        - id: geoip-route
          uri: http://localhost:7850
          predicates:
            - Path=/api/v1/**
          filters:
            - TokenRelay=
            - name: Retry
              args:
                retries: 30
                methods: GET
                backoff:
                  firstBackoff: 10ms
                  maxBackoff: 500ms
        - id: product-route
          uri: http://localhost:7860
          predicates:
            - Path=/api/v1/**
          filters:
            - TokenRelay=
            - name: Retry
              args:
                retries: 30
                methods: GET
                backoff:
                  firstBackoff: 10ms
                  maxBackoff: 500ms

    consul:
      config:
        host: 127.0.0.1
        port: 8500
        enabled: true
resilience4j:
  circuitbreaker:
    instances:
      resourceServer:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
  timelimiter:
    configs:
      resourceServer:
        timeoutDuration: 20s

