management:
  health:
    redis:
      enabled: false
logging:
  level:
    org.springframework.cloud.gateway: TRACE

spring:
  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: spring
            client-id: client
            client-secret: secret
            scope: openid, profile, user.read
            authorization-grant-type: authorization_code
            redirect-uri: http://127.0.0.1:9888/login/oauth2/code/spring
        provider:
          spring:
            issuer-uri: http://localhost:9000
  session:
    store-type: redis
    redis:
      flush-mode: on_save
      namespace: spring:session
  data:
    redis:
      host: redis-11620.c10.us-east-1-2.ec2.cloud.redislabs.com
      port: 11620
      password: t8CSfCefoozRej8KelfXuLr7VdvzeKCJ
      username: default
  cloud:
    gateway:
      default-filters:
        - TokenRelay=
        - SaveSession
      routes:
        - id: resource-server
          uri: http://localhost:9980/
          predicates:
            - Path=/**
        - id: geo-service
          uri: http://localhost:7896/
          predicates:
            - Path=/**
        - id: catalogue-route
          uri: http://localhost:7892/
          predicates:
            - Path=/**
        - id: entite-route
          uri: http://localhost:7892/
          predicates:
            - Path=/**
        - id: geoip-route
          uri: http://localhost:7850/
          predicates:
            - Path=/api/v1/**
        - id: customer-route
          uri: http://localhost:7893/
          predicates:
            - Path=/**
          filters:

            - name: Retry
              args:
                retries: 30
                methods: GET
                backoff:
                  firstBackoff: 10ms
                  maxBackoff: 500ms

resilience4j:
  circuitbreaker:
    instances:
      resourceServer:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
  timelimiter:
    configs:
      resourceServer:
        timeoutDuration: 20s