spring:
  data:
    mongodb:
      uri: mongodb://atouts_admin:P%40%40%24%24word2121@144.91.101.48:27017/orderdb?authMechanism=DEFAULT  
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://security.atouts.org/realms/atouts-realm

# To disable Hystrix in Feign
feign:
  hystrix:
    enabled: false


# To set thread isolation to SEMAPHORE
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
# swagger-ui custom path
springdoc.swagger-ui.path: /docs/api-docs.html
#springdoc.api-docs.path : /openapi/${spring.application.name}

# Whether to resolve the multipart request lazily at the time of file or parameter access.
# Please change this to the path where you want the uploaded files to be stored.
file:
  upload-dir: E:/DossierAtouts/upload-dir

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      show-components: always
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        all: true
        http.server.requests: true
  tracing:
    sampling:
      probability: 1.0
  prometheus:
    metrics:
      export:
        step: 10s
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
 


